/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodoImport } from './routes/todo'
import { Route as TestImport } from './routes/test'
import { Route as SvgWireImport } from './routes/svg-wire'
import { Route as SprayImport } from './routes/spray'
import { Route as PathTestImport } from './routes/path-test'
import { Route as PathImport } from './routes/path'
import { Route as PaintImport } from './routes/paint'
import { Route as LoaderAnimationImport } from './routes/loader-animation'
import { Route as LandingPageImport } from './routes/landing-page'
import { Route as IslandImport } from './routes/island'
import { Route as GooImport } from './routes/goo'
import { Route as ClockImport } from './routes/clock'
import { Route as AssessmentImport } from './routes/assessment'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TodoRoute = TodoImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRoute,
} as any)

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const SvgWireRoute = SvgWireImport.update({
  id: '/svg-wire',
  path: '/svg-wire',
  getParentRoute: () => rootRoute,
} as any)

const SprayRoute = SprayImport.update({
  id: '/spray',
  path: '/spray',
  getParentRoute: () => rootRoute,
} as any)

const PathTestRoute = PathTestImport.update({
  id: '/path-test',
  path: '/path-test',
  getParentRoute: () => rootRoute,
} as any)

const PathRoute = PathImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRoute,
} as any)

const PaintRoute = PaintImport.update({
  id: '/paint',
  path: '/paint',
  getParentRoute: () => rootRoute,
} as any)

const LoaderAnimationRoute = LoaderAnimationImport.update({
  id: '/loader-animation',
  path: '/loader-animation',
  getParentRoute: () => rootRoute,
} as any)

const LandingPageRoute = LandingPageImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRoute,
} as any)

const IslandRoute = IslandImport.update({
  id: '/island',
  path: '/island',
  getParentRoute: () => rootRoute,
} as any)

const GooRoute = GooImport.update({
  id: '/goo',
  path: '/goo',
  getParentRoute: () => rootRoute,
} as any)

const ClockRoute = ClockImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRoute,
} as any)

const AssessmentRoute = AssessmentImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentImport
      parentRoute: typeof rootRoute
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockImport
      parentRoute: typeof rootRoute
    }
    '/goo': {
      id: '/goo'
      path: '/goo'
      fullPath: '/goo'
      preLoaderRoute: typeof GooImport
      parentRoute: typeof rootRoute
    }
    '/island': {
      id: '/island'
      path: '/island'
      fullPath: '/island'
      preLoaderRoute: typeof IslandImport
      parentRoute: typeof rootRoute
    }
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageImport
      parentRoute: typeof rootRoute
    }
    '/loader-animation': {
      id: '/loader-animation'
      path: '/loader-animation'
      fullPath: '/loader-animation'
      preLoaderRoute: typeof LoaderAnimationImport
      parentRoute: typeof rootRoute
    }
    '/paint': {
      id: '/paint'
      path: '/paint'
      fullPath: '/paint'
      preLoaderRoute: typeof PaintImport
      parentRoute: typeof rootRoute
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathImport
      parentRoute: typeof rootRoute
    }
    '/path-test': {
      id: '/path-test'
      path: '/path-test'
      fullPath: '/path-test'
      preLoaderRoute: typeof PathTestImport
      parentRoute: typeof rootRoute
    }
    '/spray': {
      id: '/spray'
      path: '/spray'
      fullPath: '/spray'
      preLoaderRoute: typeof SprayImport
      parentRoute: typeof rootRoute
    }
    '/svg-wire': {
      id: '/svg-wire'
      path: '/svg-wire'
      fullPath: '/svg-wire'
      preLoaderRoute: typeof SvgWireImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/clock': typeof ClockRoute
  '/goo': typeof GooRoute
  '/island': typeof IslandRoute
  '/landing-page': typeof LandingPageRoute
  '/loader-animation': typeof LoaderAnimationRoute
  '/paint': typeof PaintRoute
  '/path': typeof PathRoute
  '/path-test': typeof PathTestRoute
  '/spray': typeof SprayRoute
  '/svg-wire': typeof SvgWireRoute
  '/test': typeof TestRoute
  '/todo': typeof TodoRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/clock': typeof ClockRoute
  '/goo': typeof GooRoute
  '/island': typeof IslandRoute
  '/landing-page': typeof LandingPageRoute
  '/loader-animation': typeof LoaderAnimationRoute
  '/paint': typeof PaintRoute
  '/path': typeof PathRoute
  '/path-test': typeof PathTestRoute
  '/spray': typeof SprayRoute
  '/svg-wire': typeof SvgWireRoute
  '/test': typeof TestRoute
  '/todo': typeof TodoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/clock': typeof ClockRoute
  '/goo': typeof GooRoute
  '/island': typeof IslandRoute
  '/landing-page': typeof LandingPageRoute
  '/loader-animation': typeof LoaderAnimationRoute
  '/paint': typeof PaintRoute
  '/path': typeof PathRoute
  '/path-test': typeof PathTestRoute
  '/spray': typeof SprayRoute
  '/svg-wire': typeof SvgWireRoute
  '/test': typeof TestRoute
  '/todo': typeof TodoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/clock'
    | '/goo'
    | '/island'
    | '/landing-page'
    | '/loader-animation'
    | '/paint'
    | '/path'
    | '/path-test'
    | '/spray'
    | '/svg-wire'
    | '/test'
    | '/todo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/clock'
    | '/goo'
    | '/island'
    | '/landing-page'
    | '/loader-animation'
    | '/paint'
    | '/path'
    | '/path-test'
    | '/spray'
    | '/svg-wire'
    | '/test'
    | '/todo'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/clock'
    | '/goo'
    | '/island'
    | '/landing-page'
    | '/loader-animation'
    | '/paint'
    | '/path'
    | '/path-test'
    | '/spray'
    | '/svg-wire'
    | '/test'
    | '/todo'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  ClockRoute: typeof ClockRoute
  GooRoute: typeof GooRoute
  IslandRoute: typeof IslandRoute
  LandingPageRoute: typeof LandingPageRoute
  LoaderAnimationRoute: typeof LoaderAnimationRoute
  PaintRoute: typeof PaintRoute
  PathRoute: typeof PathRoute
  PathTestRoute: typeof PathTestRoute
  SprayRoute: typeof SprayRoute
  SvgWireRoute: typeof SvgWireRoute
  TestRoute: typeof TestRoute
  TodoRoute: typeof TodoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  ClockRoute: ClockRoute,
  GooRoute: GooRoute,
  IslandRoute: IslandRoute,
  LandingPageRoute: LandingPageRoute,
  LoaderAnimationRoute: LoaderAnimationRoute,
  PaintRoute: PaintRoute,
  PathRoute: PathRoute,
  PathTestRoute: PathTestRoute,
  SprayRoute: SprayRoute,
  SvgWireRoute: SvgWireRoute,
  TestRoute: TestRoute,
  TodoRoute: TodoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/assessment",
        "/clock",
        "/goo",
        "/island",
        "/landing-page",
        "/loader-animation",
        "/paint",
        "/path",
        "/path-test",
        "/spray",
        "/svg-wire",
        "/test",
        "/todo"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/assessment": {
      "filePath": "assessment.tsx"
    },
    "/clock": {
      "filePath": "clock.tsx"
    },
    "/goo": {
      "filePath": "goo.tsx"
    },
    "/island": {
      "filePath": "island.tsx"
    },
    "/landing-page": {
      "filePath": "landing-page.tsx"
    },
    "/loader-animation": {
      "filePath": "loader-animation.tsx"
    },
    "/paint": {
      "filePath": "paint.tsx"
    },
    "/path": {
      "filePath": "path.tsx"
    },
    "/path-test": {
      "filePath": "path-test.tsx"
    },
    "/spray": {
      "filePath": "spray.tsx"
    },
    "/svg-wire": {
      "filePath": "svg-wire.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/todo": {
      "filePath": "todo.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
